### ISSUE TITLE
Import error with Basic Usage examples

### ISSUE THREAD

**Issue by palazzef** [bbaillif/bioactive_conformation_predictor#1]
Hi, thanks a lot for your work.

I have some conformations and I wanted to rank them based on one of your pretrained models. 

1) I have created a new conda env, changing from torch-geometric==2.0.5 to 2.0.4 because pip couldn't find 2.0.5 version. 

2) Then I downloaded the pretrained models and tried the first option provided in the Readme under basic usage (I think there is a small typo there, from model**s**):
from model import ComENetModel
from rankers import ModelRanker
checkpoint_path = "/my_path/pretrained_models/random_split_comenet.ckpt"
model = ComENetModel.load_from_checkpoint(checkpoint_path)

That's the error I get:
  File "try.py", line 1, in <module>
    from model import ComENetModel
  File "/my_path/bioactive_conformation_predictor/model/__init__.py", line 1, in <module>
    from .conf_pred_model import ConfPredModel
  File "/my_path/bioactive_conformation_predictor/model/conf_pred_model.py", line 9, in <module>
    from data.featurizer import MolFeaturizer
  File "/my_path/bioactive_conformation_predictor/data/featurizer/__init__.py", line 2, in <module>
    from .pyg_featurizer import PyGFeaturizer
  File "/my_path/bioactive_conformation_predictor/data/featurizer/pyg_featurizer.py", line 13, in <module>
    from data.utils import MolConverter
  File "/my_path/bioactive_conformation_predictor/data/utils/__init__.py", line 1, in <module>
    from .pdbbind import PDBbind
  File "/my_path/bioactive_conformation_predictor/data/utils/pdbbind.py", line 11, in <module>
    from data.preprocessing import MolStandardizer
  File "/my_path/bioactive_conformation_predictor/data/preprocessing/__init__.py", line 1, in <module>
    from .conf_generator import ConfGenerator
  File "/my_path/bioactive_conformation_predictor/data/preprocessing/conf_generator.py", line 6, in <module>
    from data.utils import MolConverter
ImportError: cannot import name 'MolConverter' from 'data.utils' (/my_path/bioactive_conformation_predictor/data/utils/__init__.py)

3) I also tried the second option of the same Readme me section:
from data.split import RandomSplit
data_split = RandomSplit() 
model = ComENetModel.get_model_for_data_split(data_split)

Traceback (most recent call last):
  File "try2.py", line 1, in <module>
    from data.split import RandomSplit
  File "/my_path/bioactive_conformation_predictor/data/split/__init__.py", line 1, in <module>
    from .data_split import DataSplit
  File "/my_path/bioactive_conformation_predictor/data/split/data_split.py", line 14, in <module>
    from conf_ensemble import ConfEnsembleLibrary
  File "/my_path/bioactive_conformation_predictor/conf_ensemble/__init__.py", line 1, in <module>
    from .conf_ensemble import ConfEnsemble
  File "/my_path/bioactive_conformation_predictor/conf_ensemble/conf_ensemble.py", line 9, in <module>
    from data.preprocessing import MolStandardizer
  File "/my_path/bioactive_conformation_predictor/data/preprocessing/__init__.py", line 1, in <module>
    from .conf_generator import ConfGenerator
  File "/my_path/bioactive_conformation_predictor/data/preprocessing/conf_generator.py", line 6, in <module>
    from data.utils import MolConverter
  File "/my_path/bioactive_conformation_predictor/data/utils/__init__.py", line 1, in <module>
    from .pdbbind import PDBbind
  File "/my_path/bioactive_conformation_predictor/data/utils/pdbbind.py", line 11, in <module>
    from data.preprocessing import MolStandardizer
ImportError: cannot import name 'MolStandardizer' from 'data.preprocessing' (/my_path/bioactive_conformation_predictor/data/preprocessing/__init__.py)

Could you please help me to understand what I am doing wrong? Thanks a lot.

**Comment by bbaillif** [comment]
Hi, thank you for the bug report, and my apologies for the late reply.

I see, the problem came from some circular imports following my latest refactoring (that maybe was not caught by the train_models.py or evaluate_rankers.py scripts).
I modified the repository to put all the modules in a bioconfpred directory, you can pull the latest repository version!
You can now also install the package by going to the root directory and using ```pip install . -e``` if you want to use bioconfpred in any favorite Python environment!
You should then be able to call bioconfpred.model.

I also realized the models needed config if not created from a data_split. I added a new basic instruction example:
```python
from bioconfpred.model import ComENetModel
from bioconfpred.ranker import ModelRanker
from bioconfpred.params import COMENET_CONFIG
# A model requires a config. For ComENet, we load COMENET_CONFIG
config = COMENET_CONFIG
# Models were trained using data splits. In evaluation mode, we can set the data_split to None
config['data_split'] = None
checkpoint_path = "/path/to/your/favorite/model_checkpoint.p"
model = ComENetModel.load_from_checkpoint(checkpoint_path, 
                                          config=config)
ranker = ModelRanker(model)
mol = yourFavoriteMoleculeWithConformers
ranks = ranker.rank_molecule(mol)
```

Please come back to me if this fix works so I can close the issue (and if not, I'll fix it !)

Cheers,

Benoit

**Comment by palazzef** [comment]
Hi Benoit, 

Thanks a lot for the prompt reply and for the changes and suggestions. 

After upgrading torch-geometric from 2.0.4 to 2.1.0 (apparently 'DimeNetPlusPlus' wasnt present in 2.0.4 version), and changing some calls from ccdc to rdkit I was able to run your script, but I still got the following error:

You may want to define your own root directory, currently setting to "./"
Traceback (most recent call last):
  File "try.py", line 9, in <module>
    model = ComENetModel.load_from_checkpoint(checkpoint_path, config=config)
  File "/my_path/anaconda3/envs/bioconfpred/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 161, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/my_path/anaconda3/envs/bioconfpred/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 209, in _load_model_state
    keys = model.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/my_path/anaconda3/envs/bioconfpred/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1498, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ComENetModel:
        size mismatch for atomistic_nn.interaction_blocks.0.lin_feature1.lin1.weight: copying a param with shape torch.Size([256, 12]) from checkpoint, the shape in current model is torch.Size([64, 12]).
        size mismatch for atomistic_nn.interaction_blocks.0.lin_feature1.lin2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 64]).
        size mismatch for atomistic_nn.interaction_blocks.0.lin_feature2.lin1.weight: copying a param with shape torch.Size([256, 6]) from checkpoint, the shape in current model is torch.Size([64, 6]).
        size mismatch for atomistic_nn.interaction_blocks.0.lin_feature2.lin2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 64]).
        size mismatch for atomistic_nn.interaction_blocks.1.lin_feature1.lin1.weight: copying a param with shape torch.Size([256, 12]) from checkpoint, the shape in current model is torch.Size([64, 12]).
        size mismatch for atomistic_nn.interaction_blocks.1.lin_feature1.lin2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 64]).
        size mismatch for atomistic_nn.interaction_blocks.1.lin_feature2.lin1.weight: copying a param with shape torch.Size([256, 6]) from checkpoint, the shape in current model is torch.Size([64, 6]).
        size mismatch for atomistic_nn.interaction_blocks.1.lin_feature2.lin2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 64]).
        size mismatch for atomistic_nn.interaction_blocks.2.lin_feature1.lin1.weight: copying a param with shape torch.Size([256, 12]) from checkpoint, the shape in current model is torch.Size([64, 12]).
        size mismatch for atomistic_nn.interaction_blocks.2.lin_feature1.lin2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 64]).
        size mismatch for atomistic_nn.interaction_blocks.2.lin_feature2.lin1.weight: copying a param with shape torch.Size([256, 6]) from checkpoint, the shape in current model is torch.Size([64, 6]).
        size mismatch for atomistic_nn.interaction_blocks.2.lin_feature2.lin2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 64]).
        size mismatch for atomistic_nn.interaction_blocks.3.lin_feature1.lin1.weight: copying a param with shape torch.Size([256, 12]) from checkpoint, the shape in current model is torch.Size([64, 12]).
        size mismatch for atomistic_nn.interaction_blocks.3.lin_feature1.lin2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 64]).
        size mismatch for atomistic_nn.interaction_blocks.3.lin_feature2.lin1.weight: copying a param with shape torch.Size([256, 6]) from checkpoint, the shape in current model is torch.Size([64, 6]).
        size mismatch for atomistic_nn.interaction_blocks.3.lin_feature2.lin2.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 64]).


This is the script that I am using:

from bioconfpred.model import ComENetModel
from bioconfpred.ranker import ModelRanker
from bioconfpred.params import COMENET_CONFIG
config = COMENET_CONFIG
config['data_split'] = None
checkpoint_path = "/my_path/bioactive_conformation_predictor/pretrained_models/random_split_comenet.ckpt"
model = ComENetModel.load_from_checkpoint(checkpoint_path, config=config)
ranker = ModelRanker(model)


"random_split_comet.ckpt" is one of the model from your repo on figshare. 

Thanks a lot for the support.

**Comment by bbaillif** [comment]
Hi,
My guess is that the error is coming from the DIG (dive-into-graphs) package that coded the ComENet model. Since the 1.0.0 version used in this project, they added a middle_channels=64 input parameter to the model (that I think was 256 when they first implemented it but then changed to 64) ending up changing the default architecture of the model.
Maybe the DIG package was automatically updated (i.e. when you upgraded torch-geometric from 2.0.4 to 2.1.0 or handled the ccdc dependancies) ?

I modified the bioconfpred.yml file, by changing the torch-geometric dependancy to 2.1.0 (no idea why they removed the 2.0.5 snapshot), and removing the ccdc dependancy (letting the user install it in case you want to create your own database for training, or for the docking workflow).
Therefore I would suggest to [remove the previous bioconfpred environement](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#removing-an-environment) and reinstall it with the updated yml file.

Let me know if you need any additional help and if this fixed the issue.

Cheers!

**Comment by palazzef** [comment]
Hi Benoit,

Thanks a lot again. After few changes, I made it:

1- Not having the CSD API (thanks for "try import") I had to remove the "Molecule" type from "mol_converter.py"
Eg.:
def rdkit_conf_to_ccdc_mol(self, 
                               rdkit_mol: Mol, 
                               conf_id: int = 0) -> **Molecule**:
                               
2- I had an issue with an import from torch_geometric (2.1.0):
File "/my_path/anaconda3/envs/bioconfpred2/lib/python3.7/site-packages/dig/threedgraph/method/comenet/comenet.py", line 3, in <module>
    from torch_geometric.nn.acts import swish
ModuleNotFoundError: No module named 'torch_geometric.nn.acts'

On a forum I found the solution:
try:
     from torch_geometric.nn.acts import swish
except ImportError:
     from torch_geometric.nn.resolver import swish

Now everything seems to work fine. 
Thanks a lot for the support!!
